export const environment = {
  NEXTAUTH_URL: process.env.NEXTAUTH_URL!,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET!,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID!,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET!,
  GOOGLE_REFRESH_TOKEN: process.env.GOOGLE_REFRESH_TOKEN!,
  GOOGLE_ROOT_FOLDER_ID: process.env.GOOGLE_ROOT_FOLDER_ID!,
  DATABASE_URL: process.env.DATABASE_URL!,
  DATABASE_URL_DEV: process.env.DATABASE_URL_DEV!,
  DATABASE_URL_PROD: process.env.DATABASE_URL_PROD!,
};
