name: Prisma
on:
  push:
    branches: [master, dev]
    paths: [prisma/migrations/**]

jobs:
  prod:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install packages
        run: npm install
      - name: Run prisma
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.ProdDb }}
  dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install packages
        run: npm install
      - name: Run prisma
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DevDb }}
